export DOTFILES_DIR=$HOME/config/dotfiles
source "$DOTFILES_DIR/shell/common.sh"

setopt completealiases

unsetopt correct_all
alias rspec='nocorrect rspec'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source '/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh'
source '/usr/local/opt/zsh-history-substring-search/share/zsh-history-substring-search/zsh-history-substring-search.zsh'

autoload -U promptinit; promptinit
prompt pure

# setup zsh completion system
# https://stackoverflow.com/questions/26462667/git-completion-not-working-in-zsh-on-os-x-yosemite-with-homebrew
export FPATH="/usr/local/share/zsh-completions:/usr/local/share/zsh/site-functions:$FPATH"
autoload -U compinit && compinit
zmodload -i zsh/complist

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source /usr/local/opt/zsh-history-substring-search/share/zsh-history-substring-search/zsh-history-substring-search.zsh

##############################################################################
# History Configuration
##############################################################################
HISTSIZE=5000               # How many lines of history to keep in memory
HISTFILE=~/.zsh_history     # Where to save history to disk
SAVEHIST=20000              # Number of history entries to save to disk
HISTDUP=erase               # Erase duplicates in the history file
setopt    appendhistory     # Append history to the history file (no overwriting)
setopt    sharehistory      # Share history across terminals
setopt incappendhistory     # Immediately append to the history file, not just when a term is killed

source "$DOTFILES_DIR/shell/last-working-dir.plugin.zsh"

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /Users/lu/bin/vault vault
eval "$(rbenv init - --no-rehash)"

export PATH="$HOME/.nodenv/bin:$PATH"

eval "$(nodenv init -)"
