export DOTFILES_DIR=$HOME/config/dotfiles
source "$DOTFILES_DIR/shell/common.sh"

TERM='xterm-256color'

DISABLE_UPDATE_PROMPT='true' # http://stackoverflow.com/a/25876379

unsetopt correct_all
alias rspec='nocorrect rspec'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source '/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh'
source '/usr/local/opt/zsh-history-substring-search/share/zsh-history-substring-search/zsh-history-substring-search.zsh'

autoload -U promptinit; promptinit
prompt pure

eval "$(rbenv init - --no-rehash)"

export PATH="$HOME/.nodenv/bin:$PATH"

eval "$(nodenv init -)"
