(source "gnu" "http://elpa.gnu.org/packages/")
(source "melpa" "http://melpa.milkbox.net/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")
(source "org" "http://orgmode.org/elpa/")


(depends-on "cask")
(depends-on "pallet")

(depends-on "zenburn-theme")
(depends-on "rainbow-mode")
(depends-on "rainbow-delimiters")

(depends-on "ack-and-a-half")
(depends-on "projectile")

(depends-on "magit")
(depends-on "git-gutter")

(depends-on "auto-complete")

(depends-on "flycheck")

(depends-on "markdown-mode")
(depends-on "wc-mode")
(depends-on "yaml-mode")
(depends-on "haml-mode")
(depends-on "python-mode")

(depends-on "id-manager")
