(source gnu)
(source melpa)
(source marmalade)
(source org)

;; packaging
(depends-on "cask")
(depends-on "pallet")

;; styling
(depends-on "zenburn-theme")
(depends-on "rainbow-delimiters")
(depends-on "wc-mode")
(depends-on "highlight-indent-guides")

;; prettifying
(depends-on "aggressive-indent")

;; incremental search
(depends-on "ivy")
(depends-on "counsel")
(depends-on "swiper")

;; the silver searcher integration
(depends-on "ag")

;; project management
(depends-on "projectile")
(depends-on "undo-tree")

;; Make Emacs use the $PATH set up by the user's shell
(depends-on "exec-path-from-shell")

;; git
(depends-on "magit")
(depends-on "git-gutter")

;; linting
(depends-on "flycheck")

;; modes for coding languages
(depends-on "markdown-mode")
(depends-on "yaml-mode")
(depends-on "python-mode")
(depends-on "json-mode")
(depends-on "web-mode")
(depends-on "js2-mode")
(depends-on "go-mode")

;; org-mode
(depends-on "ob-go")

;; completion & ide-like features
(depends-on "company")
(depends-on "company-lsp")
(depends-on "lsp-mode")
(depends-on "lsp-ui")

;; package configuration
(depends-on "use-package")