(add-to-list 'load-path "~/.emacs.d/mine")

(require 'set_emacs_server)
(require 'set_package_manager)
(require 'set_theme)
(require 'set_shortcuts)
(require 'set_dir_management)
(require 'set_hooks)
(require 'set_my_customization)
(require 'set_password_management)
(require 'set_yaml_tools)
(require 'set_ruby_env)
(require 'set_haskell_env)
(require 'set_misc)
